version: '3'

services:
  backend:
    build: backend
    working_dir: /app/backend
    # volumes:
    #   - ./backend:/app/backend
  client:
    build: frontend
    working_dir: /app/frontend
    ports:
      - "3000:80"
